export type GlossaryCategory =
  | "Basic Terms"
  | "Placement Essentials"
  | "Abbreviations"
  | "OSCE"
  | "Medications"
  | "Clinical Conditions"
  | "Observations & Vitals";

export type GlossaryPopulation = "general" | "adult" | "paediatric";

export type GlossaryTerm = {
  id: string;
  term: string;
  category: GlossaryCategory;
  population: GlossaryPopulation;
  shortDefinition: string;
  premium: boolean;
  pronunciation?: string;
  whyItMatters?: string;
  exampleInPractice?: string;
  osceWording?: string;
  redFlags?: string[];
  commonMistakes?: string[];
  quizQuestion?: {
    question: string;
    options: string[];
    answerIndex: number;
    explanation: string;
  };
};

export const glossaryPopulations: { value: GlossaryPopulation; label: string }[] = [
  { value: "general", label: "All Patients" },
  { value: "adult", label: "Adult" },
  { value: "paediatric", label: "Paediatric" },
];

export const glossaryCategories: GlossaryCategory[] = [
  "Basic Terms",
  "Placement Essentials",
  "Abbreviations",
  "OSCE",
  "Medications",
  "Clinical Conditions",
  "Observations & Vitals",
];

export const glossaryTerms: GlossaryTerm[] = [
  // BASIC TERMS (for first placement)
  {
    id: "nurse",
    term: "Nurse",
    category: "Basic Terms",
    population: "general",
    shortDefinition: "A registered healthcare professional who provides care, support, and education to patients.",
    premium: false,
  },
  {
    id: "patient",
    term: "Patient",
    category: "Basic Terms",
    population: "general",
    shortDefinition: "A person receiving medical care or treatment.",
    premium: false,
  },
  {
    id: "ward",
    term: "Ward",
    category: "Basic Terms",
    population: "general",
    shortDefinition: "A hospital area where patients stay for treatment and care.",
    premium: false,
  },
  {
    id: "handover",
    term: "Handover",
    category: "Placement Essentials",
    population: "general",
    shortDefinition: "The process of passing patient information and responsibility to another healthcare professional or team.",
    premium: false,
  },
  {
    id: "multidisciplinary-team",
    term: "Multidisciplinary Team (MDT)",
    category: "Placement Essentials",
    population: "general",
    shortDefinition: "A group of healthcare professionals from different backgrounds working together for patient care.",
    premium: false,
  },
  {
    id: "aseptic-technique",
    term: "Aseptic Technique",
    category: "Placement Essentials",
    population: "general",
    shortDefinition: "Practices that prevent contamination by pathogens during procedures.",
    premium: false,
  },
  {
    id: "personal-protective-equipment",
    term: "Personal Protective Equipment (PPE)",
    category: "Placement Essentials",
    population: "general",
    shortDefinition: "Equipment such as gloves, aprons, and masks used to protect staff and patients from infection.",
    premium: false,
  },
  {
    id: "vital-signs",
    term: "Vital Signs",
    category: "Basic Terms",
    population: "general",
    shortDefinition: "Clinical measurements that indicate the state of a patient’s essential body functions (e.g., temperature, pulse, respiration, blood pressure).",
    premium: false,
  },
  // ...existing code...
  {
    id: "sbar",
    term: "SBAR",
    category: "Placement Essentials",
    population: "general",
    shortDefinition: "Situation, Background, Assessment, Recommendation – the gold standard framework for clinical handovers.",
    premium: false,
    pronunciation: "S-bar",
    whyItMatters: "Ensures clear, structured communication between healthcare professionals. Reduces errors and improves patient safety.",
    exampleInPractice: "When calling the doctor about a deteriorating patient, use SBAR to give them all the info they need quickly.",
    osceWording: "I'm using SBAR to hand over: Situation – Mrs Jones has become increasingly breathless...",
  },
  {
    id: "news2",
    term: "NEWS2",
    category: "Observations & Vitals",
    population: "adult",
    shortDefinition: "National Early Warning Score 2 – a scoring system to detect deteriorating patients early.",
    premium: false,
    pronunciation: "News-two",
    whyItMatters: "Helps you spot patients who are getting sicker before they crash. A score of 5+ needs escalation!",
    exampleInPractice: "You calculate NEWS2 every time you do observations – the score tells you how urgent the response should be.",
    osceWording: "The patient's NEWS2 score is 6, which indicates a medium clinical risk requiring urgent review.",
  },
  {
    id: "prn",
    term: "PRN",
    category: "Abbreviations",
    population: "general",
    shortDefinition: "Pro re nata – 'as needed'. Medications given when required rather than at set times.",
    premium: false,
    pronunciation: "P-R-N or 'pro ree nah-tah'",
    whyItMatters: "You need to assess whether the patient actually needs the medication before giving PRN drugs.",
    exampleInPractice: "Paracetamol PRN means you check if the patient has pain before giving it, not just giving it routinely.",
  },
  {
    id: "stat",
    term: "STAT",
    category: "Abbreviations",
    population: "general",
    shortDefinition: "Statim – immediately. A one-off dose that needs to be given right now.",
    premium: false,
    pronunciation: "Stat (rhymes with cat)",
    whyItMatters: "STAT medications are urgent – drop what you're doing and give them straight away!",
    exampleInPractice: "Doctor prescribes 'Adrenaline 500mcg IM STAT' during anaphylaxis – give it immediately.",
  },
  {
    id: "spo2",
    term: "SpO2",
    category: "Observations & Vitals",
    population: "general",
    shortDefinition: "Peripheral oxygen saturation – the percentage of haemoglobin carrying oxygen, measured by pulse oximetry.",
    premium: false,
    pronunciation: "S-P-O-two",
    whyItMatters: "Quick, non-invasive way to check if your patient is getting enough oxygen. Normal is usually 94-98%.",
    exampleInPractice: "Put the probe on a warm finger, wait for a good waveform, then record the reading.",
    redFlags: ["SpO2 <92% on air", "Sudden drop from baseline", "Poor waveform signal"],
  },
  {
    id: "tachycardia",
    term: "Tachycardia",
    category: "Observations & Vitals",
    population: "general",
    shortDefinition: "Heart rate faster than 100 beats per minute in adults.",
    premium: false,
    pronunciation: "Tak-ee-KAR-dee-ah",
    whyItMatters: "Can indicate pain, anxiety, infection, dehydration, blood loss, or cardiac problems. Always investigate the cause!",
    exampleInPractice: "Your patient's HR is 115 – check for pain, fever, fluid status, and review their NEWS2.",
    redFlags: ["HR >130", "Associated with chest pain", "Low blood pressure", "Altered consciousness"],
  },
  {
    id: "bd",
    term: "BD",
    category: "Abbreviations",
    population: "general",
    shortDefinition: "Bis die – twice daily. Medication to be given two times a day.",
    premium: false,
    pronunciation: "B-D or 'bis dee'",
  },
  {
    id: "tds",
    term: "TDS",
    category: "Abbreviations",
    population: "general",
    shortDefinition: "Ter die sumendum – three times daily.",
    premium: false,
    pronunciation: "T-D-S",
  },
  {
    id: "qds",
    term: "QDS",
    category: "Abbreviations",
    population: "general",
    shortDefinition: "Quater die sumendum – four times daily.",
    premium: false,
    pronunciation: "Q-D-S",
  },
  {
    id: "po",
    term: "PO",
    category: "Abbreviations",
    population: "general",
    shortDefinition: "Per os – by mouth (oral administration).",
    premium: false,
    pronunciation: "P-O or 'per oss'",
  },
  {
    id: "iv",
    term: "IV",
    category: "Abbreviations",
    population: "general",
    shortDefinition: "Intravenous – into or within a vein.",
    premium: false,
    pronunciation: "I-V",
  },
  {
    id: "im",
    term: "IM",
    category: "Abbreviations",
    population: "general",
    shortDefinition: "Intramuscular – injection into muscle tissue.",
    premium: false,
    pronunciation: "I-M",
  },
  {
    id: "sc",
    term: "SC/SubCut",
    category: "Abbreviations",
    population: "general",
    shortDefinition: "Subcutaneous – injection under the skin.",
    premium: false,
    pronunciation: "S-C or sub-cute",
  },
  {
    id: "bradycardia",
    term: "Bradycardia",
    category: "Observations & Vitals",
    population: "general",
    shortDefinition: "Heart rate slower than 60 beats per minute in adults.",
    premium: false,
    pronunciation: "Brad-ee-KAR-dee-ah",
    redFlags: ["HR <40", "Symptomatic (dizzy, fainting)", "Associated with chest pain"],
  },
  {
    id: "hypertension",
    term: "Hypertension",
    category: "Clinical Conditions",
    population: "adult",
    shortDefinition: "High blood pressure – typically BP >140/90 mmHg.",
    premium: false,
    pronunciation: "Hy-per-TEN-shun",
  },
  {
    id: "hypotension",
    term: "Hypotension",
    category: "Clinical Conditions",
    population: "general",
    shortDefinition: "Low blood pressure – typically BP <90/60 mmHg.",
    premium: false,
    pronunciation: "Hy-po-TEN-shun",
    redFlags: ["Associated with tachycardia", "Reduced consciousness", "Signs of shock"],
  },

  // PREMIUM TERMS
  {
    id: "sepsis",
    term: "Sepsis",
    category: "Clinical Conditions",
    population: "general",
    shortDefinition: "Life-threatening organ dysfunction caused by the body's response to infection.",
    premium: true,
    pronunciation: "SEP-sis",
    whyItMatters: "Sepsis kills. Early recognition and the Sepsis 6 bundle within 1 hour saves lives. Time is critical!",
    exampleInPractice: "Patient with UTI now has NEWS2 of 7, temperature 38.5°C, and looks unwell – think sepsis and escalate immediately.",
    osceWording: "I'm concerned this patient may have sepsis. I will escalate urgently and initiate the Sepsis 6 bundle.",
    redFlags: ["NEWS2 ≥5", "Lactate >2", "Altered mental state", "Mottled skin", "Non-blanching rash"],
    commonMistakes: ["Waiting for blood results before escalating", "Not giving antibiotics within 1 hour", "Missing subtle early signs"],
    quizQuestion: {
      question: "What is the target time for giving IV antibiotics in suspected sepsis?",
      options: ["Within 3 hours", "Within 1 hour", "Within 6 hours", "When cultures come back"],
      answerIndex: 1,
      explanation: "Antibiotics should be given within 1 hour of sepsis recognition. Each hour of delay increases mortality.",
    },
  },
  {
    id: "anaphylaxis",
    term: "Anaphylaxis",
    category: "Clinical Conditions",
    population: "general",
    shortDefinition: "Severe, life-threatening allergic reaction affecting multiple body systems.",
    premium: true,
    pronunciation: "An-ah-fil-AK-sis",
    whyItMatters: "Can kill within minutes. Adrenaline is the only life-saving treatment – don't delay!",
    exampleInPractice: "Patient develops swollen lips, wheeze and rash after penicillin – give IM adrenaline immediately and call for help.",
    osceWording: "This patient is showing signs of anaphylaxis. I will give IM adrenaline 500mcg immediately and call the resus team.",
    redFlags: ["Airway swelling", "Stridor", "Severe wheeze", "Hypotension", "Altered consciousness"],
    commonMistakes: ["Giving antihistamines instead of adrenaline first", "Giving adrenaline IV instead of IM", "Not calling for help"],
    quizQuestion: {
      question: "What is the first-line treatment for anaphylaxis?",
      options: ["IV hydrocortisone", "IM adrenaline", "Nebulised salbutamol", "IV chlorphenamine"],
      answerIndex: 1,
      explanation: "IM adrenaline is the ONLY first-line treatment for anaphylaxis. Everything else is supportive.",
    },
  },
  {
    id: "hypoglycaemia",
    term: "Hypoglycaemia",
    category: "Clinical Conditions",
    population: "general",
    shortDefinition: "Low blood glucose – typically <4 mmol/L. Causes confusion, sweating, tremor.",
    premium: true,
    pronunciation: "Hy-po-gly-SEE-mee-ah",
    whyItMatters: "Can cause seizures, unconsciousness and brain damage. Quick treatment with glucose is essential.",
    exampleInPractice: "Diabetic patient is sweaty, confused and shaky with BM of 2.8 – give fast-acting glucose immediately.",
    osceWording: "This patient has symptomatic hypoglycaemia with a blood glucose of 2.8. I will give oral glucose if they can swallow safely.",
    redFlags: ["BM <3", "Unconscious", "Unable to swallow", "Seizures", "No improvement after treatment"],
    commonMistakes: ["Giving insulin instead of glucose", "Not rechecking BM after treatment", "Forgetting to give long-acting carbs after"],
  },
  {
    id: "aki",
    term: "AKI",
    category: "Clinical Conditions",
    population: "adult",
    shortDefinition: "Acute Kidney Injury – sudden decline in kidney function over hours to days.",
    premium: true,
    pronunciation: "A-K-I",
    whyItMatters: "Can be reversible if caught early. Stop nephrotoxic drugs and give fluids!",
    exampleInPractice: "Patient's creatinine has doubled since yesterday – think AKI, check fluid status, review medications.",
    osceWording: "This patient has AKI stage 2. I will ensure adequate hydration and review their medication chart for nephrotoxins.",
    redFlags: ["No urine output", "Potassium >6", "Fluid overload", "Acidosis"],
    commonMistakes: ["Continuing NSAIDs", "Not catheterising to monitor output", "Giving too much fluid in heart failure"],
  },
  {
    id: "dka",
    term: "DKA",
    category: "Clinical Conditions",
    population: "general",
    shortDefinition: "Diabetic Ketoacidosis – dangerous complication of diabetes with high glucose, ketones, and acidosis.",
    premium: true,
    pronunciation: "D-K-A",
    whyItMatters: "Medical emergency requiring IV fluids, insulin infusion, and close monitoring. Can be fatal.",
    exampleInPractice: "Type 1 diabetic with vomiting, abdominal pain, fruity breath and BM of 28 – this is DKA, escalate urgently.",
    osceWording: "I suspect DKA based on hyperglycaemia, ketones, and clinical presentation. I will escalate for urgent medical review.",
    redFlags: ["pH <7.1", "Potassium abnormalities", "GCS <12", "Severe dehydration"],
    commonMistakes: ["Giving insulin bolus (use infusion!)", "Not replacing potassium", "Reducing glucose too quickly"],
    quizQuestion: {
      question: "What is the initial fluid of choice in DKA?",
      options: ["5% dextrose", "0.9% sodium chloride", "Hartmann's solution", "Colloid"],
      answerIndex: 1,
      explanation: "0.9% sodium chloride (normal saline) is the initial fluid for DKA resuscitation.",
    },
  },
  {
    id: "copd",
    term: "COPD",
    category: "Clinical Conditions",
    population: "adult",
    shortDefinition: "Chronic Obstructive Pulmonary Disease – progressive lung disease causing breathing difficulties.",
    premium: true,
    pronunciation: "C-O-P-D",
    whyItMatters: "Patients may need controlled oxygen therapy. Too much O2 can be harmful! Target SpO2 88-92%.",
    exampleInPractice: "COPD patient with exacerbation – give nebulisers, controlled oxygen, and consider steroids/antibiotics.",
    osceWording: "This patient has a COPD exacerbation. I will titrate oxygen to target SpO2 88-92% and initiate nebulised bronchodilators.",
    redFlags: ["Rising CO2 (hypercapnia)", "Drowsiness", "Confusion", "Respiratory failure"],
    commonMistakes: ["Giving high-flow oxygen", "Not checking ABG in severe cases", "Forgetting to continue home inhalers"],
  },
  {
    id: "ae-assessment",
    term: "A-E Assessment",
    category: "OSCE",
    population: "general",
    shortDefinition: "Airway, Breathing, Circulation, Disability, Exposure – systematic approach to assess acutely unwell patients.",
    premium: true,
    pronunciation: "A to E",
    whyItMatters: "The universal approach to any deteriorating patient. Always start with Airway and work through systematically.",
    exampleInPractice: "Patient collapses – you start A-E: check airway is open, listen for breathing, feel pulse, check AVPU, then expose to look for clues.",
    osceWording: "I will perform a systematic A-E assessment, starting with Airway...",
    redFlags: ["Any airway compromise", "RR <8 or >25", "SpO2 <92%", "HR <40 or >130", "BP <90 systolic", "GCS <12"],
    commonMistakes: ["Skipping straight to E", "Not calling for help early", "Forgetting to reassess after interventions"],
    quizQuestion: {
      question: "In an A-E assessment, what does 'D' stand for?",
      options: ["Drugs", "Disability", "Diagnosis", "Documentation"],
      answerIndex: 1,
      explanation: "D = Disability. Assess neurological status using AVPU or GCS, check pupils, and blood glucose.",
    },
  },
  {
    id: "delirium",
    term: "Delirium",
    category: "Clinical Conditions",
    population: "adult",
    shortDefinition: "Acute confusion with fluctuating awareness – NOT the same as dementia. Often reversible.",
    premium: true,
    pronunciation: "Deh-LEER-ee-um",
    whyItMatters: "Common in hospital, especially elderly. Look for underlying cause: infection, constipation, medications, pain!",
    exampleInPractice: "Elderly patient suddenly confused overnight – check for UTI, constipation, review sedating medications.",
    osceWording: "This patient has developed acute delirium. I will assess for reversible causes using a structured approach.",
    redFlags: ["Sudden onset", "Visual hallucinations", "Hyperactive/agitated", "New focal neurology (consider stroke)"],
    commonMistakes: ["Assuming it's dementia", "Not looking for underlying cause", "Sedating the patient unnecessarily"],
  },
  {
    id: "consent",
    term: "Informed Consent",
    category: "OSCE",
    population: "general",
    shortDefinition: "Patient agreement to treatment after being given clear information about risks, benefits and alternatives.",
    premium: true,
    pronunciation: "Con-SENT",
    whyItMatters: "Patients have the right to decide what happens to their body. No consent = assault!",
    exampleInPractice: "Before inserting a catheter, explain what you're doing, why, risks, and check they agree.",
    osceWording: "I would like to explain the procedure, including its risks and benefits, and ensure you have the opportunity to ask questions.",
    commonMistakes: ["Assuming consent", "Not explaining risks", "Continuing when patient withdraws consent"],
  },
  {
    id: "escalation",
    term: "Escalation",
    category: "Placement Essentials",
    population: "general",
    shortDefinition: "Communicating concerns about a deteriorating patient to senior staff using a structured approach.",
    premium: true,
    whyItMatters: "Junior staff save lives by recognising deterioration and escalating early. Never be afraid to call for help!",
    exampleInPractice: "NEWS2 has increased to 6 – use SBAR to call the doctor and clearly state you need urgent review.",
    osceWording: "Based on this patient's deterioration, I am escalating to the medical team for urgent review.",
    commonMistakes: ["Waiting too long", "Not using SBAR", "Not being assertive enough about concerns"],
  },
  {
    id: "paracetamol",
    term: "Paracetamol",
    category: "Medications",
    population: "general",
    shortDefinition: "First-line analgesic and antipyretic. Max dose 4g/day in adults. Liver toxic in overdose.",
    premium: true,
    pronunciation: "Para-SET-a-mol",
    whyItMatters: "Most commonly used painkiller but overdose causes severe liver damage. Check total daily dose!",
    exampleInPractice: "Patient on co-codamol asking for paracetamol PRN – check they're not exceeding 4g/day total!",
    redFlags: ["Already had 4g today", "Liver disease", "Malnourished/low weight", "Signs of overdose"],
    commonMistakes: ["Not checking for paracetamol in combination products", "Giving IV when oral would work"],
  },
  {
    id: "morphine",
    term: "Morphine",
    category: "Medications",
    population: "general",
    shortDefinition: "Strong opioid analgesic. Causes respiratory depression, constipation, nausea. Needs careful monitoring.",
    premium: true,
    pronunciation: "MOR-feen",
    whyItMatters: "Powerful painkiller but dangerous if misused. Always monitor respiratory rate and sedation level.",
    exampleInPractice: "Post-op patient in severe pain – give morphine as prescribed but monitor RR closely (should stay >8).",
    redFlags: ["RR <8", "Over-sedation", "Pin-point pupils", "Hypotension"],
    commonMistakes: ["Not monitoring after administration", "Not having naloxone available", "Forgetting anti-emetic and laxative"],
  },
  {
    id: "insulin",
    term: "Insulin",
    category: "Medications",
    population: "general",
    shortDefinition: "Hormone that lowers blood glucose. High-risk medication requiring careful dose checking.",
    premium: true,
    pronunciation: "IN-soo-lin",
    whyItMatters: "Insulin errors are one of the most common medication errors. Always double-check with a colleague!",
    exampleInPractice: "Drawing up insulin – check the prescription, the vial, the dose, and get a second checker before giving.",
    redFlags: ["Wrong type given", "Wrong dose", "Given without food", "Patient vomiting (can't eat)"],
    commonMistakes: ["Confusing units", "Mixing up fast and slow-acting", "Not checking BM before giving"],
  },
  {
    id: "cannulation",
    term: "Cannulation",
    category: "OSCE",
    population: "general",
    shortDefinition: "Inserting a small plastic tube (cannula) into a vein for IV access.",
    premium: true,
    pronunciation: "CAN-you-lay-shun",
    whyItMatters: "Essential skill for IV medications, fluids, and blood taking. Practice makes perfect!",
    osceWording: "I will explain the procedure, gain consent, prepare my equipment, apply a tourniquet, and identify a suitable vein.",
    commonMistakes: ["Not applying tourniquet tight enough", "Going through the vein", "Not securing properly", "Forgetting to flush"],
  },
  {
    id: "catheterisation",
    term: "Catheterisation",
    category: "OSCE",
    population: "general",
    shortDefinition: "Inserting a urinary catheter to drain the bladder. Aseptic technique essential!",
    premium: true,
    pronunciation: "CATH-et-er-eye-zay-shun",
    whyItMatters: "Invasive procedure with infection risk. Only catheterise when clinically indicated.",
    osceWording: "I will gain consent, maintain aseptic technique throughout, and document the procedure and residual volume.",
    commonMistakes: ["Breaking aseptic technique", "Not using enough lubricant", "Inflating balloon before urine drains", "Not documenting"],
  },
  
  // PAEDIATRIC-SPECIFIC TERMS
  {
    id: "pews",
    term: "PEWS",
    category: "Observations & Vitals",
    population: "paediatric",
    shortDefinition: "Paediatric Early Warning Score – age-appropriate scoring system for detecting deterioration in children.",
    premium: true,
    pronunciation: "Pews",
    whyItMatters: "Children deteriorate differently to adults. PEWS uses age-appropriate parameters and parental concern as triggers!",
    exampleInPractice: "6-year-old with breathing difficulty – use PEWS chart specific to their age, not adult NEWS2.",
    osceWording: "I will calculate the PEWS score using the age-appropriate chart and escalate if the score triggers concern.",
    redFlags: ["Any elevation in PEWS", "Parental concern", "Child not interacting/playing", "Reduced wet nappies"],
    commonMistakes: ["Using adult normal values", "Ignoring parental concern", "Not using age-appropriate parameters"],
  },
  {
    id: "paeds-normal-vitals",
    term: "Paediatric Normal Vital Signs",
    category: "Observations & Vitals",
    population: "paediatric",
    shortDefinition: "Age-specific normal ranges for heart rate, respiratory rate, and blood pressure in children.",
    premium: true,
    whyItMatters: "A HR of 140 in a newborn is normal, but in a teenager it's tachycardia! Always use age-appropriate ranges.",
    exampleInPractice: "Checking vitals on a 2-year-old: normal HR 80-130, RR 22-37, BP around 90/55. Know your ranges!",
    osceWording: "I will assess this child's observations against age-appropriate normal ranges.",
    redFlags: ["Values outside age-appropriate range", "Trend of deterioration", "Child unresponsive to parents"],
    commonMistakes: ["Using adult normal values", "Not knowing age-specific ranges", "Forgetting that children compensate then crash quickly"],
  },
  {
    id: "paeds-fluid-calculation",
    term: "Paediatric Fluid Calculation",
    category: "Medications",
    population: "paediatric",
    shortDefinition: "Holliday-Segar formula for maintenance fluids: 100ml/kg for first 10kg, 50ml/kg for next 10kg, 20ml/kg thereafter.",
    premium: true,
    whyItMatters: "Children need weight-based fluid calculations. Too much or too little can be dangerous!",
    exampleInPractice: "25kg child: (100×10) + (50×10) + (20×5) = 1000+500+100 = 1600ml/24hrs maintenance fluids.",
    osceWording: "I will calculate the child's maintenance fluid requirements using the Holliday-Segar formula.",
    commonMistakes: ["Using adult volumes", "Not adjusting for illness/dehydration", "Forgetting to recalculate as child grows"],
  },
  {
    id: "paeds-drug-calculation",
    term: "Paediatric Drug Dosing",
    category: "Medications",
    population: "paediatric",
    shortDefinition: "Most paediatric medications are dosed by weight (mg/kg). Always check against maximum adult dose!",
    premium: true,
    whyItMatters: "10-fold dose errors are common in paediatrics. Always double-check calculations and use mg/kg dosing!",
    exampleInPractice: "Paracetamol for a 20kg child: 15mg/kg = 300mg. Check it doesn't exceed adult max dose.",
    redFlags: ["Dose exceeds adult maximum", "Calculation errors", "Using adult doses", "Not weighing the child first"],
    commonMistakes: ["Not weighing the child", "Using estimated weight", "Forgetting to cap at adult max", "Decimal point errors"],
  },
  {
    id: "bronchiolitis",
    term: "Bronchiolitis",
    category: "Clinical Conditions",
    population: "paediatric",
    shortDefinition: "Viral chest infection in babies/young children causing wheezing, feeding difficulties, and breathing problems.",
    premium: true,
    pronunciation: "Bron-key-oh-LY-tis",
    whyItMatters: "Common reason for paediatric admission in winter. Usually RSV. Supportive care is key – no antibiotics!",
    exampleInPractice: "8-month-old with coryzal symptoms, wheeze, and poor feeding – likely bronchiolitis. Monitor for feeding <50% and dehydration.",
    osceWording: "This child has features of bronchiolitis. I will assess hydration status and monitor for red flags.",
    redFlags: ["Apnoeas", "Feeding <50%", "SpO2 <92%", "Severe respiratory distress", "Dehydration"],
    commonMistakes: ["Giving antibiotics", "Using bronchodilators routinely", "Not assessing feeding adequately"],
  },
  {
    id: "febrile-child",
    term: "Febrile Child Assessment",
    category: "Clinical Conditions",
    population: "paediatric",
    shortDefinition: "Traffic light system for assessing sick febrile children – green (low risk), amber (intermediate), red (high risk).",
    premium: true,
    whyItMatters: "Helps identify which febrile children need urgent investigation vs reassurance. Red flags = sepsis until proven otherwise!",
    exampleInPractice: "Febrile toddler who is alert, pink, playing normally = green. Pale, not drinking = amber. Mottled, floppy = RED – escalate!",
    osceWording: "I will assess this febrile child using the NICE traffic light system to determine risk category.",
    redFlags: ["Non-blanching rash", "Bile-stained vomit", "Bulging fontanelle", "Reduced consciousness", "High-pitched cry"],
    commonMistakes: ["Focusing only on temperature height", "Missing subtle early signs", "Not reassessing after antipyretics"],
  },
  {
    id: "safeguarding-paeds",
    term: "Safeguarding Children",
    category: "Placement Essentials",
    population: "paediatric",
    shortDefinition: "Protecting children from abuse and neglect. Everyone's responsibility! Report concerns even if uncertain.",
    premium: true,
    whyItMatters: "Children cannot always speak up for themselves. You might be the one who spots the signs and saves a child's life.",
    exampleInPractice: "Bruises in unusual places, inconsistent story, child withdrawn – document everything and speak to safeguarding lead.",
    osceWording: "I have concerns about this child's safety. I will document my findings and escalate to the safeguarding team.",
    redFlags: ["Unexplained injuries", "Inconsistent history", "Delayed presentation", "Inappropriate parent behaviour", "Child disclosure"],
    commonMistakes: ["Not documenting concerns", "Being afraid to raise concerns", "Assuming someone else will act"],
  },
  {
    id: "paeds-consent",
    term: "Gillick Competence",
    category: "OSCE",
    population: "paediatric",
    shortDefinition: "Legal framework allowing children under 16 to consent to treatment if they fully understand what's involved.",
    premium: true,
    pronunciation: "GILL-ick",
    whyItMatters: "A mature 14-year-old may be able to consent; an immature 15-year-old may not. It's about understanding, not age!",
    exampleInPractice: "15-year-old wants contraception without parents knowing – assess if Gillick competent to consent independently.",
    osceWording: "I will assess whether this young person has sufficient understanding to provide their own consent.",
    commonMistakes: ["Assuming all under-16s cannot consent", "Not assessing individual competence", "Breaching confidentiality unnecessarily"],
  },

  // ADULT-SPECIFIC TERMS
  {
    id: "frailty",
    term: "Frailty",
    category: "Clinical Conditions",
    population: "adult",
    shortDefinition: "State of increased vulnerability in older adults with reduced reserve to cope with stressors like illness.",
    premium: true,
    pronunciation: "FRAY-il-tee",
    whyItMatters: "Frail patients deteriorate quickly and recover slowly. Small problems can have big consequences!",
    exampleInPractice: "85-year-old with mild UTI becomes confused, falls, and can't mobilise – frailty means small infections cause big problems.",
    osceWording: "This patient has markers of frailty. I will consider their baseline function and involve the MDT in their care.",
    redFlags: ["Sudden functional decline", "Multiple falls", "Unintentional weight loss", "Confusion"],
    commonMistakes: ["Treating frailty like 'normal ageing'", "Not assessing baseline function", "Aggressive interventions without considering goals"],
  },
  {
    id: "falls-assessment",
    term: "Falls Assessment",
    category: "OSCE",
    population: "adult",
    shortDefinition: "Systematic assessment of fall risk factors including medications, vision, mobility, environment, and cognition.",
    premium: true,
    whyItMatters: "Falls cause fractures, head injuries, and loss of confidence. Prevention is better than treatment!",
    exampleInPractice: "Elderly patient had a fall – check medications (sedatives? antihypertensives?), vision, footwear, and do lying/standing BP.",
    osceWording: "I will perform a comprehensive falls assessment including medication review and postural blood pressure.",
    redFlags: ["Head injury", "Loss of consciousness", "On anticoagulation", "Multiple recent falls", "New neurological signs"],
    commonMistakes: ["Not checking postural BP", "Not reviewing medications", "Forgetting to assess cognition"],
  },
  {
    id: "polypharmacy",
    term: "Polypharmacy",
    category: "Medications",
    population: "adult",
    shortDefinition: "Taking multiple medications (often 5+) – increases risk of interactions, side effects, and confusion.",
    premium: true,
    pronunciation: "Pol-ee-FAR-ma-see",
    whyItMatters: "More medications = more risk of interactions and side effects. Regular reviews can stop inappropriate drugs!",
    exampleInPractice: "Patient on 12 medications with new confusion – could any medications be causing this? Review with pharmacist.",
    osceWording: "This patient has polypharmacy. I would recommend a medication review to assess for potentially inappropriate medications.",
    redFlags: ["New symptoms that could be drug side effects", "Drug interactions", "Non-compliance", "Cognitive impairment affecting adherence"],
    commonMistakes: ["Adding more drugs without stopping others", "Not considering deprescribing", "Not involving patient in decisions"],
  },
  {
    id: "dnar",
    term: "DNACPR",
    category: "Placement Essentials",
    population: "adult",
    shortDefinition: "Do Not Attempt Cardiopulmonary Resuscitation – a decision that CPR should not be attempted if the heart stops.",
    premium: true,
    pronunciation: "D-N-A-C-P-R",
    whyItMatters: "CPR isn't appropriate for everyone. This decision protects patients from futile, undignified interventions at end of life.",
    exampleInPractice: "End-stage cancer patient – discuss with patient/family that CPR wouldn't be appropriate and document the decision.",
    osceWording: "I understand there is a DNACPR in place. This means CPR would not be attempted, but all other treatments continue as appropriate.",
    commonMistakes: ["Thinking DNACPR means 'do not treat'", "Not discussing with patient/family", "Not documenting clearly"],
  },
  {
    id: "capacity-adults",
    term: "Mental Capacity Assessment",
    category: "OSCE",
    population: "adult",
    shortDefinition: "Two-stage legal test to determine if someone can make a specific decision at a specific time.",
    premium: true,
    whyItMatters: "Always assume capacity unless proven otherwise. Capacity is decision-specific and time-specific!",
    exampleInPractice: "Confused patient refusing blood transfusion – formally assess if they understand, retain, weigh info and communicate decision.",
    osceWording: "I will assess this patient's capacity to make this specific decision using the two-stage test.",
    commonMistakes: ["Assuming confused patients lack capacity", "Not documenting the assessment", "Making capacity decisions without proper assessment"],
  },
  {
    id: "dvt",
    term: "DVT",
    category: "Clinical Conditions",
    population: "adult",
    shortDefinition: "Deep Vein Thrombosis – blood clot in a deep vein, usually the leg. Can lead to PE if it breaks off.",
    premium: true,
    pronunciation: "D-V-T",
    whyItMatters: "DVT can become PE which kills! Prevention in hospital (compression stockings, anticoagulation) is essential.",
    exampleInPractice: "Post-op patient with swollen, painful calf – think DVT. Use Wells score and arrange investigation.",
    osceWording: "I am concerned this patient may have a DVT. I will calculate the Wells score and arrange appropriate investigation.",
    redFlags: ["Unilateral leg swelling", "Calf pain", "Warmth", "Risk factors present", "Symptoms of PE"],
    commonMistakes: ["Missing DVT in immobile patients", "Not using compression stockings", "Forgetting prophylactic anticoagulation"],
  },
  {
    id: "af",
    term: "Atrial Fibrillation",
    category: "Clinical Conditions",
    population: "adult",
    shortDefinition: "Irregular heart rhythm (irregularly irregular) that increases stroke risk. Common in older adults.",
    premium: true,
    pronunciation: "Ay-trial Fib-ril-AY-shun",
    whyItMatters: "AF causes clots to form in the heart which can travel to the brain causing stroke. Anticoagulation prevents this!",
    exampleInPractice: "Irregularly irregular pulse on examination – ECG confirms AF. Calculate CHA2DS2-VASc score for stroke risk.",
    osceWording: "This patient has atrial fibrillation. I would assess their stroke risk using CHA2DS2-VASc and consider anticoagulation.",
    redFlags: ["Very fast rate (>130)", "Haemodynamic instability", "New onset with chest pain", "Signs of heart failure"],
    commonMistakes: ["Missing irregularly irregular pulse", "Not anticoagulating when indicated", "Using aspirin instead of proper anticoagulation"],
  },
];
