import {
  Zap,
  BookOpen,
  ClipboardCheck,
  MessageCircle,
} from 'lucide-react';
import type { HubItem, HubPathway } from './hubTypes';

// ─── Children's Branch ──────────────────────────────────────────────────────

export const hubItems: HubItem[] = [
  // ===== RECOMMENDED / POPULAR =====
  {
    id: 'ae-guide',
    title: 'A\u2013E Assessment Framework',
    description: 'A step-by-step guide to airway, breathing, circulation, disability, and exposure, plus what to say when something looks wrong in an OSCE.',
    tags: ['OSCE', 'Emergency/ABCDE', 'Paeds', 'Assessment'],
    difficulty: 'Quick Win',
    isLocked: false,
    href: '/hub/resources/ae-assessment-guide',
    isRecommended: true,
  },
  {
    id: 'im-sc-injection',
    title: 'IM & SC Injections',
    description: 'How to give injections into muscle (IM) or under the skin (SC), with sites, needles, steps, and the small OSCE details people forget.',
    tags: ['Clinical Skills', 'OSCE', 'Paeds', 'Placement'],
    difficulty: 'Moderate',
    isLocked: true,
    href: '/hub/resources/im-sc-injection',
  },
  {
    id: 'ng-tube-insertion',
    title: 'NG Tube Insertion & Testing',
    description: 'How to measure, insert, and check an NG tube safely, including what NEX, pH testing, and aspirate results actually mean.',
    tags: ['Clinical Skills', 'OSCE', 'Paeds', 'Placement'],
    difficulty: 'Moderate',
    isLocked: false,
    href: '/hub/resources/ng-tube-insertion',
  },
  {
    id: 'rec-1',
    title: 'Drug Calculations Cheat Sheet',
    description: "One place for dose formulas, drip rates, and children's calculations instead of three half-matching notes.",
    tags: ['Meds & Calculations', 'OSCE', 'Placement'],
    difficulty: 'Quick Win',
    isLocked: false,
    href: '/hub/resources/drug-calculations-cheat-sheet',
    isRecommended: true,
  },
  {
    id: 'rec-3',
    title: 'Placement Survival Guide',
    description: 'The honest version of placement advice: what to expect, what helps, and how to feel less lost on shift.',
    tags: ['Placement', 'Y1 Essentials'],
    difficulty: 'Quick Win',
    isLocked: false,
    href: '/hub/resources/placement-survival',
    isRecommended: true,
  },
  {
    id: 'osce-survival',
    title: 'How to Survive Your First OSCE',
    description: 'The honest version of OSCE advice: the night before, the script to lean on when your brain blanks, and how to leave the day behind afterwards.',
    tags: ['OSCE', 'Y1 Essentials', 'Placement'],
    difficulty: 'Quick Win',
    isLocked: false,
    href: '/hub/resources/osce-survival',
    isRecommended: true,
  },
  // ===== CORE RESOURCES =====
  {
    id: '0',
    title: 'Medication Abbreviations Guide',
    description: 'The shortened words you see on drug charts, what they mean, and which ones are safer to avoid using.',
    tags: ['Meds & Calculations', 'Placement'],
    difficulty: 'Quick Win',
    isLocked: false,
    href: '/hub/resources/medication-abbreviations',
  },
  {
    id: '2',
    title: 'Sepsis 6 & Escalation',
    description: 'How to spot possible sepsis early, what Sepsis 6 includes, and why children with extra risk factors need escalation early.',
    tags: ['Paeds', 'Emergency/ABCDE', 'Critical Care', 'Placement'],
    difficulty: 'Deep Dive',
    isLocked: true,
    href: '/hub/resources/sepsis-6-escalation',
  },
  {
    id: '9',
    title: 'Medication Administration & Safety',
    description: 'The 9 rights, from the right patient to the documentation you should not skip \u2014 and the errors that catch people out.',
    tags: ['Meds & Calculations', 'OSCE', 'Placement'],
    difficulty: 'Quick Win',
    isLocked: true,
    href: '/hub/resources/9-rights-medication',
  },
  {
    id: '10',
    title: 'Palliative Care in Children',
    description: 'Palliative care principles, symptom management, communication with children and families, memory making, and what to expect as a student nurse.',
    tags: ['Paeds', 'Communication', 'Placement', 'Deep Dive'],
    difficulty: 'Deep Dive',
    isLocked: true,
    href: '/hub/resources/palliative-care-children',
  },
  {
    id: '13',
    title: 'Paediatric Vital Signs Cheat Sheet',
    description: "Normal children's observations by age, the quick red flags, and the numbers students most often mix up.",
    tags: ['Paeds', 'Y1 Essentials', 'Assessment', 'OSCE'],
    difficulty: 'Quick Win',
    isLocked: false,
    href: '/hub/resources/paeds-vital-signs-cheat-sheet',
  },
  {
    id: 'respiratory-system',
    title: 'Respiratory System & Assessment',
    description: 'How the lungs work, what "work of breathing" means, and which signs need escalation.',
    tags: ['Paeds', 'Y1 Essentials', 'Assessment', 'Emergency/ABCDE'],
    difficulty: 'Deep Dive',
    isLocked: false,
    href: '/hub/resources/respiratory-system',
    category: 'Anatomy & Physiology',
  },
  {
    id: 'cardiovascular-system',
    title: 'Cardiovascular System & Assessment',
    description: 'How the heart pumps, how blood flows, and which circulatory signs mean a child needs help early.',
    tags: ['Paeds', 'Y1 Essentials', 'Assessment', 'Emergency/ABCDE'],
    difficulty: 'Deep Dive',
    isLocked: false,
    href: '/hub/resources/cardiovascular-system',
    category: 'Anatomy & Physiology',
  },
  {
    id: 'renal-system',
    title: 'Renal System & Assessment',
    description: 'How the kidneys make urine, what urine output means, and which renal signs need escalation early.',
    tags: ['Paeds', 'Y1 Essentials', 'Assessment', 'Fluids & Electrolytes'],
    difficulty: 'Deep Dive',
    isLocked: false,
    href: '/hub/resources/renal-system',
    category: 'Anatomy & Physiology',
  },
  {
    id: 'gastrointestinal-system',
    title: 'Gastrointestinal System & Assessment',
    description: 'How the gut digests and absorbs, paediatric GI conditions, abdominal assessment, and the signs that need escalation early.',
    tags: ['Paeds', 'Y1 Essentials', 'Assessment'],
    difficulty: 'Deep Dive',
    isLocked: false,
    href: '/hub/resources/gastrointestinal-system',
    category: 'Anatomy & Physiology',
  },
  {
    id: 'dehydration',
    title: 'Dehydration & Fluid Replacement',
    description: 'Types of dehydration, how to grade severity at the bedside, when to use ORS vs IV fluids, and the red flags that need urgent escalation.',
    tags: ['Y1 Essentials', 'Assessment', 'Fluids & Electrolytes', 'Emergency/ABCDE'],
    difficulty: 'Deep Dive',
    isLocked: false,
    href: '/hub/resources/dehydration',
  },
  {
    id: 'brain-nervous-system',
    title: 'Brain & Nervous System Assessment',
    description: 'How the nervous system is organised, what neuro observations show, and which signs need escalation urgently.',
    tags: ['Paeds', 'Y1 Essentials', 'Assessment', 'Neuro'],
    difficulty: 'Deep Dive',
    isLocked: true,
    href: '/hub/resources/brain-nervous-system',
    category: 'Anatomy & Physiology',
  },
  {
    id: 'cell-biology',
    title: 'Cell Biology & the Body',
    description: 'How cells are built, how they communicate and divide, and why understanding the cell helps you make sense of disease, drugs, and placement.',
    tags: ['Y1 Essentials', 'Revision Plans'],
    difficulty: 'Deep Dive',
    isLocked: false,
    href: '/hub/resources/cell-biology',
    category: 'Anatomy & Physiology',
  },
  {
    id: '15',
    title: 'Y1 Pain Assessment in Children',
    description: 'Which pain tools fit which age group, and how to stop FLACC and Wong-Baker blurring into one.',
    tags: ['Paeds', 'Y1 Essentials', 'Assessment', 'OSCE'],
    difficulty: 'Moderate',
    isLocked: true,
    href: '/hub/resources/y1-pain-assessment',
  },
  {
    id: '16',
    title: 'Y1 Safeguarding Children Essentials',
    description: 'The safeguarding basics every student should know, including the signs that should make you pause and speak up.',
    tags: ['Paeds', 'Y1 Essentials', 'Placement'],
    difficulty: 'Deep Dive',
    isLocked: true,
    href: '/hub/resources/y1-safeguarding',
  },
  {
    id: '17',
    title: 'Y1 Consent & Gillick Competence',
    description: "Children's consent rules in plain English, including when an under-16 can agree for themselves and what Fraser covers.",
    tags: ['Paeds', 'Y1 Essentials', 'Ethics'],
    difficulty: 'Moderate',
    isLocked: true,
    href: '/hub/resources/y1-consent-gillick',
  },
  {
    id: '18',
    title: 'Y1 Paediatric Medications Guide',
    description: 'Common paediatric drugs and doses, weight-based calculations with worked examples, high-risk medications, and medicines management OSCE preparation.',
    tags: ['Paeds', 'Y1 Essentials', 'Meds & Calculations', 'OSCE'],
    difficulty: 'Deep Dive',
    isLocked: true,
    href: '/hub/resources/y1-paeds-medications',
  },
  {
    id: '21',
    title: 'Y1 Communicating with Children',
    description: 'How to talk to children of different ages without sounding either too babyish or too formal.',
    tags: ['Paeds', 'Y1 Essentials', 'Communication'],
    difficulty: 'Moderate',
    isLocked: true,
    href: '/hub/resources/y1-child-communication',
  },
  // ===== MORE Y1 ESSENTIALS =====
  {
    id: '22',
    title: 'Y1 Anatomy & Physiology Basics',
    description: 'The body-system basics that make lectures, symptoms, and drug actions feel less random in first year.',
    tags: ['Y1 Essentials', 'Revision Plans'],
    difficulty: 'Moderate',
    isLocked: false,
    href: '/hub/resources/y1-anatomy-physiology',
    category: 'Anatomy & Physiology',
  },
  {
    id: '23',
    title: 'Documentation & Record Keeping',
    description: 'What good nursing documentation actually looks like and how to avoid writing notes that say nothing.',
    tags: ['Y1 Essentials', 'Placement'],
    difficulty: 'Quick Win',
    isLocked: false,
    href: '/hub/resources/y1-documentation',
  },
  {
    id: '24',
    title: 'Infection Prevention & Control',
    description: 'The infection-control basics that come up everywhere, with a quiz at the end.',
    tags: ['Y1 Essentials', 'Placement', 'OSCE'],
    difficulty: 'Quick Win',
    isLocked: false,
    href: '/hub/resources/y1-infection-control',
  },
  {
    id: '25',
    title: 'Professionalism & Ethics',
    description: 'The NMC, professional boundaries, and the ethics questions that sound simple until you have to explain them clearly.',
    tags: ['Y1 Essentials', 'Ethics'],
    difficulty: 'Moderate',
    isLocked: true,
    href: '/hub/resources/y1-professionalism-ethics',
  },
  {
    id: '26',
    title: 'Theories of Development',
    description: 'The main child development theories you need for exams, translated into normal language.',
    tags: ['Paeds', 'Y1 Essentials'],
    difficulty: 'Moderate',
    isLocked: false,
    href: '/hub/resources/theories-of-development',
  },
  {
    id: '27',
    title: 'Nursing Glossary',
    description: 'A searchable bank of nursing words and abbreviations with plain-English explanations for student nurses.',
    tags: ['Y1 Essentials', 'Revision Plans'],
    difficulty: 'Quick Win',
    isLocked: false,
    href: '/hub/glossary',
  },
];

export const filterTags = [
  'Y1 Essentials',
  'OSCE',
  'Paeds',
  'Meds & Calculations',
  'Placement',
  'Revision Plans',
  'Emergency/ABCDE',
  'Deep Dive',
] as const;

export const pathways: HubPathway[] = [
  {
    id: 'osce-week',
    title: 'OSCE week',
    eyebrow: 'Start here',
    description: 'If you have got an OSCE coming up, start here for the pages people usually cram the night before.',
    itemIds: ['osce-survival', 'ae-guide', '13', 'im-sc-injection', 'rec-1'],
    icon: ClipboardCheck,
  },
  {
    id: 'first-placement',
    title: 'First placement',
    eyebrow: 'Practical pages',
    description: 'A calmer starting point for first placement when you want the practical pages open in one place.',
    itemIds: ['rec-3', '23', '25', '27'],
    icon: BookOpen,
  },
  {
    id: 'drug-calculations',
    title: 'Drug calculations',
    eyebrow: 'Quick wins',
    description: 'Keep the formulas, abbreviations, and safety checks together while you practise.',
    itemIds: ['rec-1', '0', '9'],
    icon: Zap,
  },
  {
    id: 'year-one-core',
    title: 'Year one core',
    eyebrow: 'Build the base',
    description: 'The first-year pages that come up again and again in class, on placement, and before exams.',
    itemIds: ['respiratory-system', 'cardiovascular-system', 'renal-system', 'brain-nervous-system', '13', '23', '25', '26', '27'],
    icon: BookOpen,
  },
];

export const suggestedQuestionPrompts = [
  {
    title: 'What counts as a good question here?',
    description: 'OSCE stations, placements, documentation, calculations, or where to find the right page in the hub.',
    tags: ['OSCE', 'Placement'],
  },
  {
    title: 'Need help fast?',
    description: 'Keep questions short, general, and specific enough that someone can answer clearly.',
    tags: ['Quick wins', 'Revision'],
  },
  {
    title: 'Keep it study-safe',
    description: 'No patient-identifiable details and nothing urgent that needs clinical advice.',
    tags: ['Safety', 'Good to know'],
  },
];

// ─── Adult Branch ───────────────────────────────────────────────────────────

export const adultHubItems: HubItem[] = [
  {
    id: 'adult-sepsis',
    title: 'Sepsis 6 & Escalation',
    description: 'How to spot possible sepsis early, what the first six treatment steps are, and when to escalate fast in adult care.',
    tags: ['Adult', 'Critical Care', 'Assessment', 'Placement'],
    difficulty: 'Deep Dive',
    isLocked: true,
    href: '/hub/resources/sepsis-6-escalation',
    isRecommended: true,
  },
  {
    id: 'adult-iv-fluids',
    title: 'IV Fluids & Vitals Red Flags',
    description: 'Giving fluids, reading observations, and spotting the signs that mean an adult patient may be getting more unwell.',
    tags: ['Adult', 'Fluids & Electrolytes', 'Assessment', 'Placement'],
    difficulty: 'Deep Dive',
    isLocked: true,
    href: '/hub/resources/iv-fluids-vitals',
    isRecommended: true,
  },
  {
    id: 'adult-dehydration',
    title: 'Dehydration & Fluid Replacement',
    description: 'Types of dehydration, how to grade severity at the bedside, when to use ORS vs IV fluids, and the red flags that need urgent escalation.',
    tags: ['Adult', 'Y1 Essentials', 'Assessment', 'Fluids & Electrolytes'],
    difficulty: 'Deep Dive',
    isLocked: false,
    href: '/hub/resources/dehydration',
  },
  {
    id: 'adult-pressure-area',
    title: 'Pressure Area Care Plan',
    description: 'Pressure-ulcer risk scoring, skin checks, repositioning, and the care-plan points that often come up on placement.',
    tags: ['Adult', 'Care Planning', 'Placement'],
    difficulty: 'Moderate',
    isLocked: true,
    href: '/hub/resources/pressure-area-care',
  },
  {
    id: 'adult-palliative',
    title: 'Palliative & End of Life Care',
    description: 'Palliative care principles, symptom management, syringe drivers, communication with patients and families, last days of life, and care after death.',
    tags: ['Adult', 'Communication', 'Placement', 'Deep Dive'],
    difficulty: 'Deep Dive',
    isLocked: true,
    href: '/hub/resources/palliative-care-adult',
  },
  {
    id: 'adult-medication-admin',
    title: 'Medication Administration & Safety',
    description: 'The 9 rights, common drug rounds, controlled drugs, covert administration, and the errors that catch people out on placement.',
    tags: ['Adult', 'Meds & Calculations', 'Placement', 'Y1 Essentials'],
    difficulty: 'Moderate',
    isLocked: true,
    href: '/hub/resources/9-rights-medication',
  },
  {
    id: 'adult-documentation',
    title: 'Documentation & Record Keeping',
    description: 'What good nursing documentation actually looks like, common mistakes, and how to write notes that are clear, accurate, and useful.',
    tags: ['Adult', 'Y1 Essentials', 'Placement'],
    difficulty: 'Quick Win',
    isLocked: false,
    href: '/hub/resources/y1-documentation',
  },
  {
    id: 'adult-infection-control',
    title: 'Infection Prevention & Control',
    description: 'Hand hygiene, PPE, aseptic technique, isolation precautions, and the infection control basics that come up everywhere on placement.',
    tags: ['Adult', 'Y1 Essentials', 'Placement'],
    difficulty: 'Quick Win',
    isLocked: false,
    href: '/hub/resources/y1-infection-control',
  },
  {
    id: 'adult-professionalism',
    title: 'Professionalism & Ethics',
    description: 'The NMC Code, professional boundaries, duty of candour, and the ethics questions that sound simple until you have to explain them.',
    tags: ['Adult', 'Y1 Essentials', 'Ethics'],
    difficulty: 'Moderate',
    isLocked: false,
    href: '/hub/resources/y1-professionalism-ethics',
  },
  {
    id: 'adult-drug-calculations',
    title: 'Drug Calculations Cheat Sheet',
    description: 'One place for dose formulas, drip rates, and unit conversions instead of three half-matching sets of notes.',
    tags: ['Adult', 'Meds & Calculations', 'OSCE', 'Placement'],
    difficulty: 'Quick Win',
    isLocked: false,
    href: '/hub/resources/drug-calculations-cheat-sheet',
  },
  {
    id: 'adult-med-abbreviations',
    title: 'Medication Abbreviations Guide',
    description: 'The shortened words you see on drug charts, what they mean, and which ones are safer to avoid using.',
    tags: ['Adult', 'Meds & Calculations', 'Placement'],
    difficulty: 'Quick Win',
    isLocked: false,
    href: '/hub/resources/medication-abbreviations',
  },
  {
    id: 'adult-placement-survival',
    title: 'Placement Survival Guide',
    description: 'The honest version of placement advice: what to expect, what helps, and how to feel less lost on shift.',
    tags: ['Adult', 'Y1 Essentials', 'Placement'],
    difficulty: 'Quick Win',
    isLocked: false,
    href: '/hub/resources/placement-survival',
  },
  {
    id: 'adult-osce-survival',
    title: 'How to Survive Your First OSCE',
    description: 'The honest version of OSCE advice: the night before, the script to lean on when your brain blanks, and how to leave the day behind afterwards.',
    tags: ['Adult', 'OSCE', 'Y1 Essentials', 'Placement'],
    difficulty: 'Quick Win',
    isLocked: false,
    href: '/hub/resources/osce-survival',
    isRecommended: true,
  },
  {
    id: 'adult-glossary',
    title: 'Nursing Glossary',
    description: 'A searchable bank of nursing words and abbreviations with plain-English explanations for student nurses.',
    tags: ['Adult', 'Revision Plans', 'Y1 Essentials'],
    difficulty: 'Quick Win',
    isLocked: false,
    href: '/hub/glossary',
  },
  {
    id: 'adult-cell-biology',
    title: 'Cell Biology & the Body',
    description: 'How cells are built, how they communicate and divide, and why understanding the cell helps you make sense of disease, drugs, and placement.',
    tags: ['Adult', 'Y1 Essentials', 'Revision Plans'],
    difficulty: 'Deep Dive',
    isLocked: false,
    href: '/hub/resources/cell-biology',
    category: 'Anatomy & Physiology',
  },
];

export const adultFilterTags = [
  'Adult',
  'Y1 Essentials',
  'Assessment',
  'Placement',
  'Communication',
  'Critical Care',
  'Care Planning',
  'Fluids & Electrolytes',
  'Meds & Calculations',
  'Ethics',
  'Revision Plans',
  'Deep Dive',
] as const;

export const adultPathways: HubPathway[] = [
  {
    id: 'adult-escalation',
    title: 'Escalation basics',
    eyebrow: 'Start here',
    description: 'Open the adult pages that help most when observations, fluids, and deterioration all need tying together quickly.',
    itemIds: ['adult-sepsis', 'adult-iv-fluids'],
    icon: ClipboardCheck,
  },
  {
    id: 'adult-first-placement',
    title: 'First placement',
    eyebrow: 'Practical pages',
    description: 'A calmer starting point for adult placement when you want the most useful pages open in one place.',
    itemIds: ['adult-placement-survival', 'adult-documentation', 'adult-infection-control', 'adult-glossary'],
    icon: BookOpen,
  },
  {
    id: 'adult-meds',
    title: 'Drug calculations',
    eyebrow: 'Quick wins',
    description: 'Keep the formulas, abbreviations, and safety checks together while you practise.',
    itemIds: ['adult-drug-calculations', 'adult-med-abbreviations', 'adult-medication-admin'],
    icon: Zap,
  },
  {
    id: 'adult-communication',
    title: 'Communication',
    eyebrow: 'Patient-facing',
    description: 'Keep calm wording for escalation, palliative care, and difficult conversations together.',
    itemIds: ['adult-palliative', 'adult-sepsis'],
    icon: MessageCircle,
  },
];

// ─── Helpers ────────────────────────────────────────────────────────────────

export function sortHubItemsAlphabetically(items: HubItem[]) {
  return [...items].sort((a, b) =>
    a.title.localeCompare(b.title, 'en', {
      sensitivity: 'base',
    }),
  );
}
